# Generated by Django 5.1.6 on 2025-04-06 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sent_timestamp', models.DateTimeField(null=True)),
                ('extra_data', models.TextField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('channel', models.IntegerField(choices=[(1, 'EMAIL'), (2, 'SMS'), (3, 'PUSH')], default=3)),
                ('type', models.IntegerField(choices=[(1, 'DEFAULT'), (2, 'JOB_AVAILABLE'), (3, 'NEW_BID'), (4, 'BID_ACCEPTED'), (5, 'BID_REJECTED'), (6, 'JOB_COMPLETED_BY_INSPECTOR'), (7, 'JOB_COMPLETED'), (8, 'JOB_CANCELED'), (9, 'NEW_MESSAGE')], default=1)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_from_user', to=settings.AUTH_USER_MODEL)),
                ('targets', models.ManyToManyField(blank=True, related_name='notifications_to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_notification_errors', to='notifications.notification')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
