# Generated by Django 5.1.4 on 2025-01-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspector',
            options={'ordering': ['-id']},
        ),
    ]
