# Generated by Django 5.1.6 on 2025-02-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('inspector', '0003_alter_inspector_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspector',
            name='cities',
        ),
        migrations.AddField(
            model_name='inspector',
            name='regions',
            field=models.ManyToManyField(blank=True, to='cities_light.region'),
        ),
    ]
