# Generated by Django 5.1.6 on 2025-02-18 17:49

import inspector.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0006_language_inspector_date_of_birth_inspector_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportdocument',
            name='document',
            field=models.FileField(upload_to='support-documents', validators=[inspector.models.file_size]),
        ),
    ]
