# Generated by Django 5.1.6 on 2025-02-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0007_alter_supportdocument_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile-picture'),
        ),
    ]
