# Generated by Django 5.1.6 on 2025-02-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0008_inspector_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='notify_im_qualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspector',
            name='notify_job_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspector',
            name='notify_new_message',
            field=models.BooleanField(default=False),
        ),
    ]
