# Generated by Django 5.1.6 on 2025-02-22 20:03

import django.db.models.deletion
import django.utils.timezone
import inspector.models
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0009_inspector_notify_im_qualified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspector',
            name='credentials',
        ),
        migrations.CreateModel(
            name='CredentialDcoument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('document', models.FileField(blank=True, null=True, upload_to='credential-documents', validators=[inspector.models.file_size])),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inspector.credential')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_documents', to='inspector.inspector')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inspector',
            name='credential',
            field=models.ManyToManyField(blank=True, through='inspector.CredentialDcoument', to='inspector.credential'),
        ),
    ]
