# Generated by Django 5.1.6 on 2025-02-22 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0010_remove_inspector_credentials_credentialdcoument_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspector',
            old_name='credential',
            new_name='credentials',
        ),
    ]
