# Generated by Django 5.1.6 on 2025-04-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0011_rename_credential_inspector_credentials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credential',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='credential',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
