# Generated by Django 5.1.6 on 2025-02-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_alter_owner_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Industries'},
        ),
    ]
