# Generated by Django 5.1.6 on 2025-02-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_alter_industry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
