# Generated by Django 5.1.6 on 2025-02-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_owner_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='owner-banner'),
        ),
        migrations.AddField(
            model_name='owner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='owner-logo'),
        ),
    ]
