# Generated by Django 5.1.6 on 2025-02-23 02:29

import utils.utils.misc
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_owner_banner_owner_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='owner-banner', validators=[utils.utils.misc.file_size]),
        ),
        migrations.AlterField(
            model_name='owner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='owner-logo', validators=[utils.utils.misc.file_size]),
        ),
    ]
