# Generated by Django 5.1.8 on 2025-04-14 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_bid_note'),
        ('payments', '0002_remove_transaction_created_by_transaction_inspector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='jobs.job'),
        ),
    ]
