# Generated by Django 5.1.8 on 2025-05-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_transaction_inspector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(10, 'Pending'), (15, 'Held'), (17, 'Processing'), (20, 'Completed'), (30, 'Failed'), (40, 'Cancelled')], default=10),
        ),
    ]
