# Generated by Django 5.1.6 on 2025-03-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'verbose_name': 'Job Category', 'verbose_name_plural': 'Job Categories'},
        ),
    ]
