# Generated by Django 5.1.6 on 2025-03-20 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0011_rename_credential_inspector_credentials'),
        ('jobs', '0002_alter_bid_options_alter_jobcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='inspector.inspector'),
        ),
    ]
