# Generated by Django 5.1.6 on 2025-03-24 14:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_magiclinktoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='job',
            name='mileage_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='job',
            name='misc_other_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_modes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('daily', 'Daily'), ('per_diem', 'Per Diem'), ('mileage', 'Mileage'), ('misc_other', 'Misc/Other')], max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='job',
            name='per_diem_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
