# Generated by Django 5.1.6 on 2025-03-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
