# Generated by Django 5.1.6 on 2025-03-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_bid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
