# Generated by Django 5.1.6 on 2025-04-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('jobs', '0010_jobfavorite'),
        ('owner', '0007_alter_owner_banner_alter_owner_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='categories',
        ),
        migrations.AddField(
            model_name='job',
            name='industries',
            field=models.ManyToManyField(blank=True, to='owner.industry'),
        ),
        migrations.AddField(
            model_name='job',
            name='regions',
            field=models.ManyToManyField(blank=True, to='cities_light.region'),
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
    ]
