# Generated by Django 5.1.6 on 2025-04-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_job_categories_job_industries_job_regions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('finished_by_inspector', 'Finished by Inspector'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='pending', max_length=21),
        ),
    ]
