# Generated by Django 5.1.6 on 2025-04-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_bid_mileage_alter_bid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
