# Generated by Django 5.1.8 on 2025-04-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_bid_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('awaiting_payment', 'Awaiting Payment'), ('started', 'Started'), ('finished_by_inspector', 'Finished by Inspector'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='pending', max_length=21),
        ),
    ]
