# Generated by Django 5.1.4 on 2024-12-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stripe_account_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_account_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_account_linked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_customer_id',
        ),
    ]
