# Generated by Django 5.1.4 on 2025-01-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_verification_email_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Verification Email Sent'),
        ),
    ]
