# Generated by Django 5.1.4 on 2025-02-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_last_verification_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverificationcode',
            name='code_type',
            field=models.CharField(choices=[('phone_verification', 'Phone Verification'), ('password_reset', 'Password Reset')], default='password_reset', max_length=50, verbose_name='Code Type'),
        ),
        migrations.AddField(
            model_name='userverificationcode',
            name='last_sent',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Sent'),
        ),
    ]
