# Generated by Django 5.1.6 on 2025-02-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biometrics_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Biometrics Key'),
        ),
    ]
