# Generated by Django 5.1.6 on 2025-02-17 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_biometrics_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userverificationcode',
            options={'verbose_name': 'User Verification Code', 'verbose_name_plural': 'User Verification Codes'},
        ),
    ]
