# Generated by Django 5.1.6 on 2025-02-18 22:23

import corrosion_one_49197.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_linkedin_user_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=corrosion_one_49197.storage_backends.AzureMediaStorage(), upload_to='profile-picture'),
        ),
    ]
