# Generated by Django 5.1.6 on 2025-02-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marketing_notifications',
            field=models.BooleanField(default=True, verbose_name='Marketing Notifications'),
        ),
    ]
