# Generated by Django 5.1.8 on 2025-04-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_supportemail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cardholder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connected Account ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_account_link',
            field=models.URLField(blank=True, null=True, verbose_name='Account Link'),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer (consumer facing) ID', max_length=255, null=True),
        ),
    ]
