# Generated by Django 5.1.8 on 2025-04-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_user_cardholder_user_stripe_account_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_payouts_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
