# Generated by Django 5.1.8 on 2025-05-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_stripe_payouts_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cta_agreement',
            field=models.BooleanField(default=False, verbose_name='CTA Agreement'),
        ),
    ]
